storage.mode=mysql
mysql.url=jdbc:mysql://localhost:3306/order_management
mysql.username=root
mysql.password=Khanh@2005

hikari.maximum-pool-size=10
hikari.minimum-idle=5
hikari.idle-timeout=30000
hikari.connection-timeout=20000